#Configuration du serveur
#Nom de l'application (utile pour Eureka et Spring Cloud)
spring.application.name=bookstore
# D�finit le port sur lequel le microservice Order & Payment sera lanc�
server.port=8085

# URL de connexion � la base MySQL
# Configuration de la base de donn�es MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/bookstore?createDatabaseIfNotExist=true
# Nom d'utilisateur de la base de donn�es
spring.datasource.username=root
# Mot de passe de la base de donn�es
#spring.datasource.password=${DB_PASSWORD}
#spring.datasource.password=root

# D�sactiver Spring Cloud Config
spring.cloud.config.enabled=false

#Configuration de JPA & Hibernate
# Affiche les requ�tes SQL ex�cut�es dans la console
spring.jpa.show-sql=true
# Hibernate met � jour les tables automatiquement
spring.jpa.hibernate.ddl-auto=update

server.servlet.context-path=/bookstore


#stripe.secret.key=${STRIPE_SECRET_KEY}
#stripe.public.key=${STRIPE_PUBLIC_KEY}


#stripe.secret.key=sk_test_51QpFthCTMfT9nYHGzaKCyo1ksHcWTzXbdwtTX19dcaXBi8UDjAyZiCopR5pZxBex9RCLmK6niQUF0mKFRCMAXZWS00GmbuIuI6
#stripe.public.key=pk_test_51QpFthCTMfT9nYHGgrpp1PbppVxXEgg4cD40boYD8Ob9kjnOJYyx3XBsRKuHHABKEtKOi4tWLGAaQcqBTQLnALUg00YaUf9nYy

# Mode fail-safe
spring.config.on-not-found=ignore
spring.config.import=optional:file:${user.dir}/.env[com.example.bookstore.config.DotenvPropertySourceFactory]

# Valeurs par défaut (pour les tests)
stripe.secret.key=${STRIPE_SECRET_KEY:sk_test_default}
stripe.public.key=${STRIPE_PUBLIC_KEY:pk_test_default}
spring.datasource.password=${DB_PASSWORD:root}