version: '3.8'

services:
  eureka-server:
    build: ./Eureka
    ports:
      - "8761:8761"
    networks:
      - booki-network


  database:
    image: mysql:5.7
    container_name: database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kaddem
      TZ: UTC
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "database"]
      interval: 5s
      timeout: 10s
      retries: 20  
    networks:
      - kaddem-net

  book-service:
    image: nousseiba/gestionlivres:latest
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    ports:
      - "8095:8095"
    networks:
      - booki-network
    depends_on:
      - eureka-server

  cart-service:
    image: nousseiba/cart:latest
    build: ./Cart
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    ports:
      - "8082:8082"
    networks:
      - booki-network
    depends_on:
      - eureka-server
      - book-service

networks:
  booki-network:
    driver: bridge

